[package]
name = "pelias-load-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
prometheus = "0.13.4"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
warp = "0.3.7"
