{
 "title": "Pelias load test",
 "time": { "from": "2024-09-16T17:48:34.491Z", "to": "2024-09-16T17:51:33.214Z" },
 "panels": [
  {
   "title": "Average request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(response_time_milliseconds_sum{job=\"load_test\"}[$__rate_interval]) / rate(response_time_milliseconds_count{job=\"load_test\"}[$__rate_interval]) / 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(status_code_counter[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(requests_total[$__rate_interval])\n",
     "legendFormat": "requests"
    }
   ]
  }
 ]
}